"""Generate a working sascfg_personal.py, so nobody has to hand-write one.

SASPy ships a 225-line commented template and no way to produce a config from
it. For an audience of SAS developers -- many of whom are not Python
developers -- "copy this file and edit the right stanza" is the step where
adoption stops. This asks a few questions instead and writes a correct file to
the durable home location.

The pure parts (region lookup, Java detection, config rendering) are separated
from the prompting so they can be tested without a terminal.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

CONFIG_NAME = "sascfg_personal.py"


def default_config_dir() -> Path:
    """Where SASPy looks in the user's home, on every platform.

    SASPy calls ``expanduser("~/.config/saspy/")`` unconditionally, so Windows
    resolves this under %USERPROFILE% rather than AppData.
    """
    return Path.home() / ".config" / "saspy"


def default_config_path() -> Path:
    return default_config_dir() / CONFIG_NAME


def authinfo_path() -> Path:
    """SASPy reads _authinfo on Windows and .authinfo elsewhere."""
    name = "_authinfo" if sys.platform.startswith("win") else ".authinfo"
    return Path.home() / name


# --- SAS OnDemand for Academics regions --------------------------------------


@dataclass(frozen=True)
class ODARegion:
    key: str
    label: str
    hosts: tuple[str, ...]


ODA_REGIONS: tuple[ODARegion, ...] = (
    ODARegion("us1", "United States (Home Region 1)",
              ("odaws01-usw2.oda.sas.com", "odaws02-usw2.oda.sas.com")),
    ODARegion("us2", "United States (Home Region 2)",
              ("odaws01-usw2-2.oda.sas.com", "odaws02-usw2-2.oda.sas.com")),
    ODARegion("eu1", "Europe (Home Region 1)",
              ("odaws01-euw1.oda.sas.com", "odaws02-euw1.oda.sas.com")),
    ODARegion("ap1", "Asia Pacific (Home Region 1)",
              ("odaws01-apse1.oda.sas.com", "odaws02-apse1.oda.sas.com")),
    ODARegion("ap2", "Asia Pacific (Home Region 2)",
              ("odaws01-apse1-2.oda.sas.com", "odaws02-apse1-2.oda.sas.com")),
)

ODA_REGIONS_BY_KEY = {r.key: r for r in ODA_REGIONS}


# --- Java discovery ----------------------------------------------------------


def _java_runs(exe: str) -> bool:
    """A path existing is not the same as a JRE being installed.

    macOS ships /usr/bin/java as a stub that exits non-zero when no runtime is
    present, so the only reliable test is running it.
    """
    try:
        p = subprocess.run([exe, "-version"], capture_output=True, text=True,
                           timeout=20)
    except (OSError, subprocess.TimeoutExpired):
        return False
    return p.returncode == 0 and "Unable to locate a Java Runtime" not in (
        p.stderr or ""
    )


def detect_java() -> str | None:
    """Find a Java executable that actually works, or None."""
    candidates: list[str] = []

    if sys.platform == "darwin":
        # Homebrew and manual installs often are not registered with
        # /usr/libexec/java_home even though they run fine.
        try:
            p = subprocess.run(["/usr/libexec/java_home"], capture_output=True,
                               text=True, timeout=20)
            if p.returncode == 0 and p.stdout.strip():
                candidates.append(str(Path(p.stdout.strip()) / "bin" / "java"))
        except (OSError, subprocess.TimeoutExpired):
            pass
        for base in sorted(Path("/Library/Java/JavaVirtualMachines").glob("*"),
                           reverse=True):
            candidates.append(str(base / "Contents" / "Home" / "bin" / "java"))
        for base in ("/opt/homebrew/opt/openjdk/bin/java",
                     "/usr/local/opt/openjdk/bin/java"):
            candidates.append(base)

    if which := shutil.which("java"):
        candidates.append(which)

    for exe in candidates:
        if Path(exe).exists() and _java_runs(exe):
            return exe
    return None


# --- config rendering --------------------------------------------------------

_HEADER = """\
# SASPy configuration generated by `sas-mcp init`.
#
# Docs: https://sassoftware.github.io/saspy/configuration.html
# Re-run `sas-mcp doctor` after editing to check this file.

SAS_config_names = [{names}]

"""


def _render_dict(name: str, entries: dict[str, Any]) -> str:
    lines = [f"{name} = {{"]
    for k, v in entries.items():
        lines.append(f"    {k!r}: {v!r},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_oda_config(region: str, name: str = "oda",
                     java: str | None = None) -> str:
    """Config for SAS OnDemand for Academics (IOM over the public internet)."""
    if region not in ODA_REGIONS_BY_KEY:
        raise ValueError(
            f"Unknown ODA region {region!r}. Choose one of: "
            f"{', '.join(ODA_REGIONS_BY_KEY)}"
        )
    entries: dict[str, Any] = {
        "java": java or "java",
        "iomhost": list(ODA_REGIONS_BY_KEY[region].hosts),
        "iomport": 8591,
        "authkey": name,
        "encoding": "utf-8",
    }
    return _HEADER.format(names=repr(name)) + _render_dict(name, entries)


def build_stdio_config(saspath: str, name: str = "local",
                       encoding: str = "utf-8") -> str:
    """Config for SAS installed locally on Linux/UNIX (no Java needed)."""
    return _HEADER.format(names=repr(name)) + _render_dict(
        name, {"saspath": saspath, "encoding": encoding}
    )


def build_ssh_config(host: str, saspath: str, user: str | None = None,
                     name: str = "remote", encoding: str = "utf-8") -> str:
    """Config for SAS on a remote UNIX host reached over SSH.

    SSH must be key-based: SASPy cannot answer a password prompt.
    """
    entries: dict[str, Any] = {
        "ssh": "ssh",
        "host": host,
        "saspath": saspath,
        "encoding": encoding,
    }
    if user:
        entries["luser"] = user
    return _HEADER.format(names=repr(name)) + _render_dict(name, entries)


def build_iom_config(host: str, port: int = 8591, name: str = "iomserver",
                     java: str | None = None, encoding: str = "utf-8") -> str:
    """Config for a SAS Workspace Server on an intranet, over IOM."""
    entries: dict[str, Any] = {
        "java": java or "java",
        "iomhost": host,
        "iomport": int(port),
        "authkey": name,
        "encoding": encoding,
    }
    return _HEADER.format(names=repr(name)) + _render_dict(name, entries)


def build_winlocal_config(sashome: str, name: str = "winlocal",
                          java: str | None = None,
                          encoding: str = "windows-1252") -> str:
    """Config for SAS installed locally on Windows (IOM via a local bridge).

    This one needs the SAS Java client jars from the SAS installation, so the
    generated classpath is a best guess that the user should verify.
    """
    base = sashome.rstrip("\\/")
    jars = [
        rf"{base}\SASDeploymentManager\9.4\products\deploywiz__94xxx__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar",
        rf"{base}\SASDeploymentManager\9.4\products\deploywiz__94xxx__prt__xx__sp0__1\deploywiz\log4j.jar",
        rf"{base}\SASDeploymentManager\9.4\products\deploywiz__94xxx__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar",
        rf"{base}\SASDeploymentManager\9.4\products\deploywiz__94xxx__prt__xx__sp0__1\deploywiz\sas.core.jar",
    ]
    body = (
        "# NOTE: verify these jar paths against your SAS installation; the\n"
        "# deploywiz directory name varies by SAS release.\n"
        "cp = ';'.join([\n"
        + "".join(f"    r{j!r},\n" for j in jars)
        + "])\n\n"
    )
    entries: dict[str, Any] = {
        "java": java or "java",
        "encoding": encoding,
        "classpath": "@CP@",
    }
    rendered = _render_dict(name, entries).replace("'@CP@'", "cp")
    return _HEADER.format(names=repr(name)) + body + rendered


# --- writing files -----------------------------------------------------------


class ConfigExists(FileExistsError):
    """Raised rather than silently overwriting an existing config."""


def write_config(text: str, path: Path | None = None,
                 force: bool = False) -> Path:
    """Write the config, refusing to clobber an existing one unless forced."""
    target = Path(path) if path else default_config_path()
    target = target.expanduser()
    if target.exists() and not force:
        raise ConfigExists(
            f"{target} already exists. Pass --force to overwrite it, or edit "
            f"it directly."
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    _restrict(target)
    return target


def _restrict(path: Path) -> None:
    """Owner-only permissions. A no-op on Windows, which ignores POSIX bits."""
    if not sys.platform.startswith("win"):
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def authinfo_has_key(key: str, path: Path | None = None) -> bool:
    p = (path or authinfo_path()).expanduser()
    if not p.is_file():
        return False
    for line in p.read_text(errors="replace").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and line.split()[0] == key:
            return True
    return False


def write_authinfo_entry(key: str, user: str, password: str,
                         path: Path | None = None,
                         force: bool = False) -> Path:
    """Append a credential line, and lock the file down.

    The password is written to disk in the clear because that is what SASPy
    reads; file permissions are the only protection, so they are enforced here
    rather than left to the user.
    """
    p = (path or authinfo_path()).expanduser()
    if authinfo_has_key(key, p) and not force:
        raise ConfigExists(
            f"{p} already has an entry named {key!r}. Edit it directly, or "
            f"re-run with --force."
        )

    existing = ""
    if p.is_file():
        existing = p.read_text(errors="replace")
        if existing and not existing.endswith("\n"):
            existing += "\n"
        if force:
            kept = [
                ln for ln in existing.splitlines()
                if not (ln.strip() and not ln.lstrip().startswith("#")
                        and ln.split()[0] == key)
            ]
            existing = "\n".join(kept) + ("\n" if kept else "")

    p.write_text(f"{existing}{key} user {user} password {password}\n")
    _restrict(p)
    return p


# --- interactive flow --------------------------------------------------------

DEPLOYMENTS = (
    ("oda", "SAS OnDemand for Academics (free, cloud)"),
    ("unix", "SAS installed locally on this Linux/UNIX machine"),
    ("winlocal", "SAS installed locally on this Windows machine"),
    ("iom", "SAS server on my network (IOM / Workspace Server)"),
    ("ssh", "SAS on a remote UNIX host over SSH"),
)


def _ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        answer = input(f"{prompt}{suffix}: ").strip()
        if answer:
            return answer
        if default is not None:
            return default


def _choose(prompt: str, options: list[tuple[str, str]]) -> str:
    print(f"\n{prompt}")
    for i, (_, label) in enumerate(options, 1):
        print(f"  {i}. {label}")
    while True:
        raw = input(f"Choice [1-{len(options)}]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1][0]
        print("  Please enter a number from the list.")


def _confirm(prompt: str, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{hint}]: ").strip().lower()
    if not raw:
        return default
    return raw.startswith("y")


def _java_or_warn() -> str | None:
    java = detect_java()
    if java:
        print(f"  Found a working Java runtime: {java}")
        return java
    print(
        "  WARNING: no working Java runtime found, and this connection type\n"
        "  needs one. The config will say 'java', which works only if a JRE is\n"
        "  on your PATH. Install one (macOS: brew install --cask temurin) and\n"
        "  set the 'java' entry to its full path."
    )
    return None


def interactive_init(force: bool = False,
                     path: Path | None = None) -> dict[str, Any]:
    """Ask what is needed, write the config, and report what was written."""
    print("\nsas-mcp init -- create a SASPy configuration\n" + "=" * 46)

    kind = _choose("Where does your SAS run?", list(DEPLOYMENTS))
    name = "oda" if kind == "oda" else _ask(
        "Name for this configuration", "sasconfig"
    )
    result: dict[str, Any] = {"deployment": kind, "config_name": name}

    if kind == "oda":
        region = _choose(
            "Which ODA home region? (shown at welcome.oda.sas.com)",
            [(r.key, r.label) for r in ODA_REGIONS],
        )
        java = _java_or_warn()
        text = build_oda_config(region, name=name, java=java)
        result["region"] = region

    elif kind == "unix":
        saspath = _ask("Full path to the SAS startup script",
                       "/opt/sasinside/SASHome/SASFoundation/9.4/sas")
        text = build_stdio_config(saspath, name=name)
        result["saspath"] = saspath

    elif kind == "winlocal":
        sashome = _ask("SASHome directory", r"C:\Program Files\SASHome")
        java = _java_or_warn()
        text = build_winlocal_config(sashome, name=name, java=java)
        result["sashome"] = sashome

    elif kind == "iom":
        host = _ask("SAS server hostname")
        port = _ask("IOM port", "8591")
        java = _java_or_warn()
        text = build_iom_config(host, int(port), name=name, java=java)
        result["host"] = host

    else:  # ssh
        host = _ask("Remote hostname")
        saspath = _ask("Full path to the SAS startup script on that host",
                       "/opt/sasinside/SASHome/SASFoundation/9.4/sas")
        user = _ask("SSH username (blank to use your local username)", "")
        print(
            "  Note: SSH must be key-based and passwordless -- SASPy cannot\n"
            "  answer a password prompt."
        )
        text = build_ssh_config(host, saspath, user or None, name=name)
        result["host"] = host

    target = write_config(text, path=path, force=force)
    result["config_path"] = str(target)
    print(f"\nWrote {target}")

    # Credentials, for the connection types that authenticate.
    if kind in {"oda", "iom"}:
        if authinfo_has_key(name) and not force:
            print(f"{authinfo_path()} already has an entry named {name!r}; "
                  f"leaving it alone.")
        elif _confirm(f"\nSave your SAS credentials to {authinfo_path()} now?"):
            import getpass

            user = _ask("SAS user name (for ODA, your SAS Profile email)")
            password = getpass.getpass("SAS password (not echoed): ")
            if password:
                p = write_authinfo_entry(name, user, password, force=force)
                print(f"Wrote credentials to {p} (permissions set to owner-only)")
                result["authinfo_path"] = str(p)
            else:
                print("No password entered; skipping.")

    print("\nNext: run `sas-mcp doctor` to verify the setup.\n")
    return result
